### PR TITLE
now the system will take only one email ID per user

### PR DESCRIPTION
**Pull request by Pankhurinyu**

### CODE REVIEW

**Review by emoltz — CHANGES_REQUESTED** [review]
This looks great, but does it only make sure the emails are unique that are already in the system? Or does it validate a new email address coming in? 
Also, I think we should put this validation on the signup form somehow... I think I saw an article about that somewhere.

**Comment by Pankhurinyu** [comment]
The new email duplicate checker can`t do anything about the records that are already stored in the database. But, for the new email IDs, if they are already there in the system, it will not let the user use the same email ID.

Also, I was earlier thinking of adding an "email checker" function to the views.py Class. But adding a single line to the models.py  file (which validates email IDs), was the shortest and quickest that I could find.

**Comment by emoltz** [comment]
got it makes sense. Yeah I will just add a zenhub issue to make sure it's present in the signup form but this lgtm

**Review by emoltz — APPROVED** [review]
lgtm

**Review by emoltz — COMMENTED** [review]
Should we wait to merge till closer to MVP? We are usually using the same email over and over to test.

**Pull request closed without merging**
