### PR TITLE
Ability to see descriptions of books on bookshelf

### PR DESCRIPTION
**Pull request by emoltz**
A few things:
- Getting the modal to work with the carousel was... very hard. Perhaps you can take a stab at it? In lieu of the one you made, I just made some buttons that will grab the book's info and populate a pop-up with the info for now.
- There are also buttons to move and delete the book but these aren't working yet -- we'll need specific db_functions for this (unless we have them already @sjeremycohen ?)

Lmk what your thoughts are!

### CODE REVIEW

**Comment by sjeremycohen** [comment]
@emoltz iirc there is a bookshelf delete function but no change shelf function. That should be easy to do this morning.

**Comment by emoltz** [comment]
Yeah I see the delete function! The only problem is getting the book id for the selected book in the carousel...

**Comment by emoltz** [comment]
latest push includes CRUD operations @michaelzachor ! 😄

**Comment by emoltz** [comment]
need to add some tests

**Comment by emoltz** [comment]
tests not working... standy

**Pull request merged**
