### PR TITLE
Add a footer

### PR DESCRIPTION
**Pull request by Pankhurinyu**

### CODE REVIEW

**Comment by emoltz** [comment]
some merge conflict that have to be resolved... maybe we should, in the future, create separate css files for different parts of the site to prevent this?

**Comment by Pankhurinyu** [comment]
Okay. Shall I create a separate CSS file for the footer ?

**Comment by emoltz** [comment]
Still some issues even after moving the css to a new file, but let me work on it and see

**Comment by emoltz** [comment]
Ok I see the issues -- not a big deal, *but* I think we should talk as a team about colors and stuff before merging

**Comment by emoltz** [comment]
needs changes to color scheme

**Pull request merged**
