### PR TITLE
added google login functionality

### PR DESCRIPTION
**Pull request by Pankhurinyu**

### CODE REVIEW

**Comment by emoltz** [comment]
@Pankhurinyu can you add the google key to Travis env vars? And can you send it to me on slack so I can add in AWS?

**Comment by Pankhurinyu** [comment]
Yeah. I added it on Tarvis CI

**Review by emoltz — CHANGES_REQUESTED** [review]
Can you try and figure out why travis is failing here?

**Comment by Pankhurinyu** [comment]
Yeah. @emoltz  
 Made a new repository and added google login function from scratch over there.

https://github.com/gcivil-nyu-org/team-3-inperson/tree/google-login-function

**Comment by Pankhurinyu** [comment]
I will close this branch then as its function is present over the new branch.

https://github.com/gcivil-nyu-org/team-3-inperson/pull/322

**Pull request closed without merging**
