### PR TITLE
Pseudo Rec Engine implemented

### PR DESCRIPTION
**Pull request by sjeremycohen**
Tests breaking locally, opening a PR bc I ran out of personal Travis credits so I need to consume gcivil credits this way

### CODE REVIEW

**Comment by sjeremycohen** [comment]
@emoltz (cc @rohan-sardana) the pseudo-rec engine code is done. Needs your review. THERE IS ALREADY A KNOWN ISSUE: IF THE USER IS NOT LOGGED IN, IT ERRORS!!!! The bookswiping page should never be exposed unless the user is logged in. But in the case where it is, it will error now!!!

**Comment by emoltz** [comment]
is there a way to direct the person to the login screen if they're not logged in? I can look into this

**Comment by sjeremycohen** [comment]
Definitely. I'm sure one of the other teams has implemented it. Also: 404 pages

**Comment by emoltz** [comment]
The 404 page thing I had set up a while ago, I even made a custom 404 page. But `DEBUG` must be set to `FALSE` in order for it to work

**Comment by sjeremycohen** [comment]
https://stackoverflow.com/questions/21123559/django-redirect-all-non-authenticated-users-to-landing-page

**Review by emoltz — APPROVED** [review]
lgtm!

**Pull request merged**
